import type {
  EmailProvider,
  Mailbox,
  WorkspaceMember,
} from "../types/emailAccount.types";

// TODO: Remove this module once the email service is wired through
export const PLACEHOLDER_PROVIDERS: readonly EmailProvider[] = [
  {
    id: "gmail",
    name: "Gmail",
    sub: "Google Workspace",
    authMethod: "oauth",
    authLabel: "OAuth 2.0",
    monogram: "G",
    tone: "danger",
    via: "Gmail API",
    consentHost: "accounts.google.com",
    domains: ["gmail.com", "googlemail.com"],
    imapHost: "imap.gmail.com",
    imapPort: 993,
    smtpHost: "smtp.gmail.com",
    smtpPort: 465,
  },
  {
    id: "outlook",
    name: "Outlook",
    sub: "Personal Microsoft",
    authMethod: "oauth",
    authLabel: "OAuth 2.0",
    monogram: "O",
    tone: "accent",
    via: "Microsoft Graph",
    consentHost: "login.microsoftonline.com",
    domains: ["outlook.com", "hotmail.com", "live.com"],
    imapHost: "outlook.office365.com",
    imapPort: 993,
    smtpHost: "smtp-mail.outlook.com",
    smtpPort: 587,
  },
  {
    id: "m365",
    name: "Microsoft 365",
    sub: "Work or school",
    authMethod: "oauth",
    authLabel: "OAuth 2.0 · Graph",
    monogram: "M",
    tone: "accent",
    via: "Microsoft Graph",
    consentHost: "login.microsoftonline.com",
    domains: [],
    imapHost: "outlook.office365.com",
    imapPort: 993,
    smtpHost: "smtp.office365.com",
    smtpPort: 587,
  },
  {
    id: "yahoo",
    name: "Yahoo Mail",
    sub: "Yahoo",
    authMethod: "app-password",
    authLabel: "App password",
    monogram: "Y",
    tone: "violet",
    via: "IMAP and SMTP",
    consentHost: null,
    domains: ["yahoo.com", "ymail.com"],
    imapHost: "imap.mail.yahoo.com",
    imapPort: 993,
    smtpHost: "smtp.mail.yahoo.com",
    smtpPort: 465,
  },
  {
    id: "private",
    name: "Private Email",
    sub: "Namecheap",
    authMethod: "app-password",
    authLabel: "App password",
    monogram: "P",
    tone: "accent",
    via: "IMAP and SMTP",
    consentHost: null,
    domains: ["privateemail.com"],
    imapHost: "mail.privateemail.com",
    imapPort: 993,
    smtpHost: "mail.privateemail.com",
    smtpPort: 465,
  },
  {
    id: "proton",
    name: "Proton Mail",
    sub: "Needs Proton Bridge",
    authMethod: "bridge-password",
    authLabel: "Bridge password",
    monogram: "Pr",
    tone: "violet",
    via: "Proton Bridge",
    consentHost: null,
    domains: ["proton.me", "protonmail.com"],
    imapHost: "127.0.0.1",
    imapPort: 1143,
    smtpHost: "127.0.0.1",
    smtpPort: 1025,
  },
  {
    id: "zoho",
    name: "Zoho Mail",
    sub: "Zoho Workplace",
    authMethod: "oauth",
    authLabel: "OAuth 2.0",
    monogram: "Z",
    tone: "warning",
    via: "Zoho Mail API",
    consentHost: "accounts.zoho.com",
    domains: ["zoho.com", "zohomail.com"],
    imapHost: "imap.zoho.com",
    imapPort: 993,
    smtpHost: "smtp.zoho.com",
    smtpPort: 465,
  },
  {
    id: "icloud",
    name: "iCloud Mail",
    sub: "Apple",
    authMethod: "app-password",
    authLabel: "App password",
    monogram: "i",
    tone: "neutral",
    via: "IMAP and SMTP",
    consentHost: null,
    domains: ["icloud.com", "me.com"],
    imapHost: "imap.mail.me.com",
    imapPort: 993,
    smtpHost: "smtp.mail.me.com",
    smtpPort: 587,
  },
  {
    id: "fastmail",
    name: "Fastmail",
    sub: "Fastmail",
    authMethod: "app-password",
    authLabel: "App password",
    monogram: "F",
    tone: "success",
    via: "IMAP and SMTP",
    consentHost: null,
    domains: ["fastmail.com", "fastmail.fm"],
    imapHost: "imap.fastmail.com",
    imapPort: 993,
    smtpHost: "smtp.fastmail.com",
    smtpPort: 465,
  },
  {
    id: "imap",
    name: "Custom IMAP / SMTP",
    sub: "Any other provider",
    authMethod: "app-password",
    authLabel: "App password",
    monogram: "::",
    tone: "neutral",
    via: "IMAP and SMTP",
    consentHost: null,
    domains: [],
    imapHost: "mail.example.com",
    imapPort: 993,
    smtpHost: "mail.example.com",
    smtpPort: 465,
  },
];

// TODO: Remove this module once the email service is wired through
export const PLACEHOLDER_MEMBERS: readonly WorkspaceMember[] = [
  {
    membershipId: "mem_priya",
    name: "Priya Raman",
    email: "priya@followaxis.com",
    role: "Admin",
    organisationId: "org_northstar",
  },
  {
    membershipId: "mem_arun",
    name: "Arun Mehta",
    email: "arun@followaxis.com",
    role: "Agent",
    organisationId: "org_northstar",
  },
  {
    membershipId: "mem_nadia",
    name: "Nadia Farouk",
    email: "nadia@followaxis.com",
    role: "Campaign Manager",
    organisationId: "org_northstar",
  },
  {
    membershipId: "mem_iris",
    name: "Iris Kaur",
    email: "iris@followaxis.com",
    role: "Analyst",
    organisationId: "org_northstar",
  },
  {
    membershipId: "mem_tom",
    name: "Tom Whitfield",
    email: "tom@followaxis.com",
    role: "Designer",
    organisationId: "org_northstar",
  },
  {
    membershipId: "mem_sofia",
    name: "Sofia Marchetti",
    email: "sofia@followaxis.com",
    role: "Agent",
    organisationId: "org_northstar",
  },
  {
    membershipId: "mem_elena",
    name: "Elena Duarte",
    email: "elena@meridianco.com",
    role: "Admin",
    organisationId: "org_meridian",
  },
  {
    membershipId: "mem_marcus",
    name: "Marcus Bell",
    email: "marcus@meridianco.com",
    role: "Agent",
    organisationId: "org_meridian",
  },
];

export const DEFAULT_ORGANISATION_ID = "org_northstar";

export const WORKSPACE_ORGANISATIONS: Readonly<Record<string, string>> = {
  northwind: "org_northstar",
  halcyon: "org_northstar",
  meridian: "org_meridian",
};

const secondsAgo = (seconds: number): string =>
  new Date(Date.now() - seconds * 1000).toISOString();

// TODO: Remove this module once the email service is wired through
export const PLACEHOLDER_MAILBOXES: readonly Mailbox[] = [
  {
    id: "mbx_priya",
    address: "priya@followaxis.com",
    displayName: "Priya Raman",
    providerId: "gmail",
    providerLabel: "Gmail",
    monogram: "PR",
    isSyncing: true,
    lastSyncedAt: secondsAgo(34),
    imapEndpoint: "imap.gmail.com:993",
    smtpEndpoint: "smtp.gmail.com:465",
    storageUsedGb: 4.2,
    storageQuotaGb: 15,
    authMethod: "oauth",
    scopeId: "reply",
    dailyCap: 120,
    sentToday: 38,
    sendingWindow: {
      days: ["mon", "tue", "wed", "thu", "fri"],
      startTime: "09:00",
      endTime: "17:00",
      timeZone: "Europe/London",
    },
    grants: [
      {
        membershipId: "mem_priya",
        name: "Priya Raman",
        email: "priya@followaxis.com",
        role: "Admin",
        canSend: true,
      },
    ],
    updatedAt: "2026-08-12T09:59:26.000Z",
  },
  {
    id: "mbx_hello",
    address: "hello@followaxis.com",
    displayName: "Follow Axis Team",
    providerId: "m365",
    providerLabel: "Microsoft 365",
    monogram: "FA",
    isSyncing: true,
    lastSyncedAt: secondsAgo(60),
    imapEndpoint: "outlook.office365.com:993",
    smtpEndpoint: "smtp.office365.com:587",
    storageUsedGb: 22.6,
    storageQuotaGb: 50,
    authMethod: "oauth",
    scopeId: "full",
    dailyCap: 80,
    sentToday: 64,
    sendingWindow: {
      days: ["mon", "tue", "wed", "thu", "fri"],
      startTime: "08:00",
      endTime: "18:00",
      timeZone: "Europe/London",
    },
    grants: [
      {
        membershipId: "mem_priya",
        name: "Priya Raman",
        email: "priya@followaxis.com",
        role: "Admin",
        canSend: true,
      },
      {
        membershipId: "mem_arun",
        name: "Arun Mehta",
        email: "arun@followaxis.com",
        role: "Agent",
        canSend: true,
      },
      {
        membershipId: "mem_nadia",
        name: "Nadia Farouk",
        email: "nadia@followaxis.com",
        role: "Campaign Manager",
        canSend: true,
      },
      {
        membershipId: "mem_iris",
        name: "Iris Kaur",
        email: "iris@followaxis.com",
        role: "Analyst",
        canSend: false,
      },
    ],
    updatedAt: "2026-08-12T09:59:00.000Z",
  },
  {
    id: "mbx_noreply",
    address: "no-reply@followaxis.com",
    displayName: "Transactional",
    providerId: "private",
    providerLabel: "Private Email",
    monogram: "NR",
    isSyncing: true,
    lastSyncedAt: secondsAgo(4 * 60),
    imapEndpoint: "mail.privateemail.com:993",
    smtpEndpoint: "mail.privateemail.com:465",
    storageUsedGb: 0.8,
    storageQuotaGb: 10,
    authMethod: "app-password",
    scopeId: null,
    dailyCap: 400,
    sentToday: 118,
    sendingWindow: {
      days: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
      startTime: "00:00",
      endTime: "23:59",
      timeZone: "Europe/London",
    },
    grants: [
      {
        membershipId: "mem_priya",
        name: "Priya Raman",
        email: "priya@followaxis.com",
        role: "Admin",
        canSend: true,
      },
    ],
    updatedAt: "2026-08-12T09:56:00.000Z",
  },
  {
    id: "mbx_northwind",
    address: "northwind@client.co",
    displayName: "Northwind Outreach",
    providerId: "outlook",
    providerLabel: "Outlook",
    monogram: "NW",
    isSyncing: false,
    lastSyncedAt: secondsAgo(2 * 60 * 60),
    imapEndpoint: "outlook.office365.com:993",
    smtpEndpoint: "smtp-mail.outlook.com:587",
    storageUsedGb: 6.1,
    storageQuotaGb: 15,
    authMethod: "oauth",
    scopeId: "send",
    dailyCap: 30,
    sentToday: 22,
    sendingWindow: {
      days: ["mon", "tue", "wed", "thu", "fri"],
      startTime: "09:30",
      endTime: "16:30",
      timeZone: "Europe/London",
    },
    grants: [
      {
        membershipId: "mem_arun",
        name: "Arun Mehta",
        email: "arun@followaxis.com",
        role: "Agent",
        canSend: true,
      },
      {
        membershipId: "mem_iris",
        name: "Iris Kaur",
        email: "iris@followaxis.com",
        role: "Analyst",
        canSend: false,
      },
    ],
    updatedAt: "2026-08-12T08:00:00.000Z",
  },
];
